import {
  ChefHat, Users, TrendingUp, Heart, Globe, BookOpen,
  Rocket, DollarSign, Clock, UtensilsCrossed, PartyPopper,
  Bike, Shield,
} from "lucide-react";
import type { CultureValue, Benefit, HowItWorksStep, Job, Testimonial } from "../types/index";

export const CULTURE_VALUES: CultureValue[] = [
  { Icon: UtensilsCrossed, label: "Excellence",  desc: "We take pride in everything we do",     color: "#E10B1C" },
  { Icon: Users,           label: "Respect",     desc: "Every team member matters",              color: "#FCD063" },
  { Icon: TrendingUp,      label: "Growth",      desc: "We promote from within",                 color: "#E10B1C" },
  { Icon: Heart,           label: "Passion",     desc: "Food is our love language",              color: "#FCD063" },
  { Icon: Globe,           label: "Community",   desc: "We give back to our neighborhoods",      color: "#E10B1C" },
];

export const BENEFITS: Benefit[] = [
  { Icon: BookOpen,        label: "Training & Development", desc: "Paid training programs from day one",   color: "#E10B1C" },
  { Icon: Rocket,          label: "Growth",                 desc: "Clear promotion pathways",              color: "#FCD063" },
  { Icon: DollarSign,      label: "Benefits",               desc: "Competitive pay + tips",                color: "#E10B1C" },
  { Icon: Clock,           label: "Flexible Schedules",     desc: "Work–life balance respected",           color: "#FCD063" },
  { Icon: UtensilsCrossed, label: "Free Meals",             desc: "Free meals on every shift",             color: "#E10B1C" },
  { Icon: PartyPopper,     label: "Team Events",            desc: "Regular team celebrations",             color: "#FCD063" },
];

export const JOBS: Job[] = [
  {
    id: "line-cook-lekki",
    title: "Line Cook",
    location: "lekki",
    locationLabel: "Lekki, Lagos",
    department: "kitchen",
    type: "Full-time",
    typeNote: "Experience preferred",
    blurb: "Prepare authentic Nigerian dishes under senior chef guidance",
    icon: ChefHat,
    about: "We're looking for a passionate Line Cook to join our Lekki kitchen team. You'll work alongside our senior chefs to prepare authentic Nigerian dishes that delight our guests every day.",
    responsibilities: [
      "Prepare ingredients and cook menu items to standard",
      "Maintain clean and organised workstation",
      "Follow recipes and portion specifications",
      "Assist with inventory and stock rotation",
      "Collaborate with team during busy service",
    ],
    requirements: [
      "1+ year kitchen experience preferred",
      "Knowledge of Nigerian cuisine is a plus",
      "Ability to work weekends and holidays",
      "Food safety certification (or willingness to obtain)",
      "Physically able to stand for long periods",
    ],
    weOffer: [
      "Competitive pay + tips",
      "Free meals on shift",
      "Paid training",
      "Opportunities for advancement",
      "Supportive team environment",
    ],
  },
  {
    id: "server-lekki",
    title: "Server / Waiter",
    location: "lekki",
    locationLabel: "Lekki, Lagos",
    department: "service",
    type: "Part-time & Full-time",
    typeNote: "Weekend availability required",
    blurb: "Provide exceptional table service to our guests",
    icon: UtensilsCrossed,
    about: "As a Server at Foodies Lekki, you'll be the face of our brand — creating warm, memorable dining experiences for every guest who walks through our doors.",
    responsibilities: [
      "Greet and seat guests with warmth and professionalism",
      "Take orders accurately and communicate with kitchen team",
      "Serve food and beverages promptly",
      "Handle guest queries and resolve concerns",
      "Maintain cleanliness of dining area",
    ],
    requirements: [
      "Previous serving or hospitality experience preferred",
      "Excellent communication and people skills",
      "Weekend availability is mandatory",
      "Ability to work in a fast-paced environment",
      "Smart, professional appearance",
    ],
    weOffer: [
      "Competitive hourly pay + tips",
      "Free meals on shift",
      "Flexible scheduling options",
      "Career development support",
      "Positive team culture",
    ],
  },
  {
    id: "kitchen-steward-lekki",
    title: "Kitchen Steward",
    location: "lekki",
    locationLabel: "Lekki, Lagos",
    department: "kitchen",
    type: "Full-time",
    typeNote: "Early morning shifts",
    blurb: "Maintain kitchen cleanliness and assist the prep team",
    icon: Shield,
    about: "Our Kitchen Stewards are the backbone of a smooth-running kitchen. You'll keep our workspace spotless and support the culinary team so they can focus on creating great food.",
    responsibilities: [
      "Wash and sanitise all kitchen equipment and utensils",
      "Maintain cleanliness of kitchen floors and surfaces",
      "Assist prep team with basic food preparation tasks",
      "Manage waste and recycling responsibly",
      "Receive and store deliveries",
    ],
    requirements: [
      "Reliable, punctual and hard-working",
      "Comfortable with early morning starts",
      "Physical stamina for active role",
      "Attention to hygiene and food safety",
      "Team player with positive attitude",
    ],
    weOffer: [
      "Steady full-time income",
      "Free meals on shift",
      "Paid food safety training",
      "Clear pathway to kitchen prep roles",
      "Supportive management",
    ],
  },
  {
    id: "shift-supervisor-abuja",
    title: "Shift Supervisor",
    location: "abuja",
    locationLabel: "Maitama, Abuja",
    department: "operations",
    type: "Full-time",
    typeNote: "2+ years supervisory experience required",
    blurb: "Lead the floor team during busy service periods",
    icon: Users,
    about: "We're looking for an experienced Shift Supervisor to lead our Abuja floor team. You'll ensure smooth service delivery, mentor junior staff, and uphold Foodies' standards of excellence.",
    responsibilities: [
      "Oversee daily floor and kitchen operations during your shift",
      "Manage staff scheduling and briefings",
      "Handle escalated guest concerns professionally",
      "Monitor quality standards and resolve issues in real time",
      "Complete end-of-shift reports and handovers",
    ],
    requirements: [
      "2+ years supervisory experience in hospitality",
      "Strong leadership and communication skills",
      "Ability to remain calm under pressure",
      "Familiarity with restaurant POS systems",
      "Flexibility for morning, afternoon and evening shifts",
    ],
    weOffer: [
      "Competitive supervisory salary",
      "Free meals on shift",
      "Management training programmes",
      "Fast-track to Restaurant Manager",
      "Performance bonuses",
    ],
  },
  {
    id: "delivery-driver-abuja",
    title: "Delivery Driver",
    location: "abuja",
    locationLabel: "Maitama, Abuja",
    department: "operations",
    type: "Part-time",
    typeNote: "Must have own bike and valid licence",
    blurb: "Join our upcoming in-house delivery fleet",
    icon: Bike,
    isPhase4: true,
    about: "Foodies is building its own delivery fleet (Phase 4) and we want passionate riders to be part of it from day one. Register your interest now and be first in line when we launch.",
    responsibilities: [
      "Collect orders promptly from our kitchen",
      "Deliver to customers within designated zones",
      "Maintain food quality and temperature during transit",
      "Represent Foodies with professionalism",
      "Use the Foodies app for order tracking",
    ],
    requirements: [
      "Valid motorcycle licence",
      "Own reliable motorcycle",
      "Knowledge of Lagos / Abuja road networks",
      "Smartphone with data plan",
      "Clean driving record",
    ],
    weOffer: [
      "Per-delivery earnings + bonuses",
      "Flexible hours",
      "App-based order management",
      "Early-mover advantage in Foodies fleet",
      "Growth into senior rider roles",
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "I started as a kitchen steward 3 years ago. Today, I'm a line cook training for sous chef. Foodies believes in growing their own.",
    name: "Ade",
    role: "Senior Line Cook",
    location: "Lekki",
    initials: "A",
    color: "#E10B1C",
    image:"https://i.pinimg.com/1200x/87/cb/ca/87cbca3b19212fa120d706d8c0be593f.jpg"
  },
  {
    quote: "The team here is family. We work hard, but we laugh harder. Foodies supported me through hospitality school with flexible scheduling.",
    name: "Fatima",
    role: "Server",
    location: "Maitama",
    initials: "F",
    color: "#FCD063",
    image: "https://i.pinimg.com/736x/99/28/b6/9928b66c3aea1f88930d9390444af13e.jpg"
  },
  {
    quote: "I came in knowing nothing about hospitality. The paid training and mentorship here turned me into someone my whole family is proud of.",
    name: "Chukwuemeka",
    role: "Kitchen Steward → Line Cook",
    location: "Lekki",
    initials: "C",
    color: "#E10B1C",
    image: "https://i.pinimg.com/736x/fc/e6/93/fce693e4be192e6943e4a0fc3957a005.jpg"
  },
];

export const HOW_IT_WORKS: HowItWorksStep[] = [
  { step: "01", label: "Browse Roles",      desc: "Find the position that matches your skills and location" },
  { step: "02", label: "Apply Online",      desc: "Complete our short form and attach your CV in under 5 minutes" },
  { step: "03", label: "We Review",         desc: "Our team reviews every application within 5 business days" },
  { step: "04", label: "Interview & Offer", desc: "Shortlisted candidates are invited for a brief in-person or call interview" },
];